Repository algoan/nestjs-components, pull requests merged in 2020-10, with the labels that each got.

#67 fix: fixed update last rel calculation
  packages/pagination/src/add-link-header.interceptor.ts
Labels: bug

#68 feat: improved content range calculation
  packages/pagination/src/add-link-header.interceptor.ts
  packages/pagination/test/add-link-header.test.ts
Labels: bug

#73 feat: set default limit
  packages/pagination/README.md
  packages/pagination/src/add-link-header.interceptor.ts
  packages/pagination/src/index.ts
  packages/pagination/src/mongo-pagination-param.decorator.ts
  packages/pagination/test/add-link-header.test.ts
  packages/pagination/test/helpers.ts
Labels: enhancement

#75 typo in import
  packages/google-pubsub-microservice/README.md
Labels: documentation

#81 feat: be able to filter topic names to subscribe
  packages/google-pubsub-microservice/README.md
  packages/google-pubsub-microservice/src/GooglePubSubServer.ts
  packages/google-pubsub-microservice/test/GooglePubSubServer.test.ts
  packages/google-pubsub-microservice/test/test-app/app.controller.ts
Labels: enhancement

#79 fix content-range for 1 result
  packages/pagination/src/add-link-header.interceptor.ts
  packages/pagination/test/add-link-header.test.ts
  packages/pagination/test/helpers.ts
Labels: bug
